name: QA CI/CD

on:
  push:
    branches: [qa]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Instala Node 14.x
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
      
    - name: Install Dependencies
      run: |
        npm install
    
    - name: Ejecutar Pruebas y Cobertura
      run: |
        npm run test
        npm run coverage
        npm run coverage:report 
  
  deploy:
    name: deploy lambda function
    runs-on: ubuntu-latest
    environment: qa
    steps:
    - uses: actions/checkout@v1
    - name: AWS Lambda Deploy
      uses: appleboy/lambda-action@master
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: us-east-1
        function_name: Drive-API-QA
        zip_file: drive-api.zip
        dry_run: true
